# SPDX-FileCopyrightText: 2025 Jack Henry
# 
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["**/*.json", "**/*.svg", "NOTICE"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jack Henry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/*.png"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jack Henry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [ "**/assets/fonts/RobotoFlex-VariableFont.woff2"
]
precedence = "override"
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = "Copyright 2017 The Roboto Flex Project Authors" 

[[annotations]]
path = [ "**/assets/fonts/RobotoMono-Italic-VariableFont.woff2",
 "**/assets/fonts/RobotoMono-VariableFont.woff2"
]
precedence = "override"
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = "Copyright 2015 Christian Robertson" 

[[annotations]]
path = [
    "packages/jh-ui/.storybook/public/images/markus-winkler-DJoG5GsXfMw-unsplash.jpg",
]
precedence = "override"
SPDX-License-Identifier = "LicenseRef-Unsplash"
SPDX-FileCopyrightText = "Photo by Markus Winkler on Unsplash"