# SPDX-FileCopyrightText: 2025 Jack Henry
# 
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = "**/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Jack Henry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/*.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Jack Henry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [ "packages/jh-core/assets/fonts/RobotoFlex-VariableFont.woff2",
"packages/jh-core/platforms/web/assets/fonts/RobotoFlex-VariableFont.woff2"
]
precedence = "aggregate"
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = "Copyright 2017 The Roboto Flex Project Authors" 

[[annotations]]
path = [ "packages/jh-core/assets/fonts/RobotoMono-Italic-VariableFont.woff2",
 "packages/jh-core/platforms/web/assets/fonts/RobotoMono-Italic-VariableFont.woff2",
 "packages/jh-core/assets/fonts/RobotoMono-VariableFont.woff2",
 "packages/jh-core/platforms/web/assets/fonts/RobotoMono-VariableFont.woff2"
]
precedence = "aggregate"
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = "Copyright 2015 Christian Robertson" 

[[annotations]]
paths = [
    "packages/jh-ui/.storybook/public/images/markus-winkler-DJoG5GsXfMw-unsplash.jpg",
]
precedence = "aggregate"
SPDX-License-Identifier = "NOASSERTION"
SPDX-FileCopyrightText = "Photo by Markus Winkler on Unsplash"

[[annotations]]
paths = [
    "packages/jh-ui/.storybook/public/logos/chrome-logo.svg",
    "packages/jh-ui/.storybook/public/logos/firefox-logo.svg",
    "packages/jh-ui/.storybook/public/logos/safari-logo.svg",
]
precedence = "aggregate"
SPDX-License-Identifier = "NOASSERTION"
SPDX-FileCopyrightText = "Chrome, Firefox, and Safari Logos are Trademarks of their respective owners."