blank_issues_enabled: false
contact_links:
    - name: Questions or Discussion
      url: https://github.com/Banno/design-system/discussions
      about: Please post general questions or discussion topics here.