# SPDX-FileCopyrightText: 2025 Jack Henry
#
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
    - name: Questions or Discussion
      url: https://github.com/Banno/jack-henry-design-system/discussions
      about: Please post general questions or discussion topics here.