# SPDX-FileCopyrightText: 2025 Jack Henry
#
# SPDX-License-Identifier: Apache-2.0

name: 'Chromatic-Dev'
on: 
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  chromatic-deployment:
    permissions:
      contents: read
    name: Chromatic Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/jh-elements
          exitZeroOnChanges: true
          skip: "${{ !contains(github.event.pull_request.labels.*.name, 'status: visual review') }}"
