# SPDX-FileCopyrightText: 2025 Jack Henry
#
# SPDX-License-Identifier: Apache-2.0
name: REUSE Compliance Check
permissions:
  contents: read

on: [push, pull_request]

jobs:
  reuse-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: REUSE lint
        uses: fsfe/reuse-action@v6